In [27]:
import numpy as np

a =np.zeros((4,4))

a[0:3, 0:3] = 2

print(a)

[[2. 2. 2. 0.]
 [2. 2. 2. 0.]
 [2. 2. 2. 0.]
 [0. 0. 0. 0.]]


In [28]:
a[:,0:2] += 3 
print(a)

[[5. 5. 2. 0.]
 [5. 5. 2. 0.]
 [5. 5. 2. 0.]
 [3. 3. 0. 0.]]


In [29]:
print(a[0,...])

[5. 5. 2. 0.]


In [31]:
data = np.arange(10)
data2 = np.arange (20)

print(data)
print(data2)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
