In [10]:
l1 = [1,23,3]
l2 = [2,3,45]

a1 = np.array(l1)
a2 = np.array(l2)


print(l1+l2)
print(a1*a2)
print(a1**5)

[1, 23, 3, 2, 3, 45]
[  2  69 135]
[      1 6436343     243]


In [4]:
l3 = [0]*3
for i in range(3):
    l3[i] = l2[i]+ l1[i]
print(l3)    
# adding respective elements of list together.

[3, 26, 48]


In [6]:
import numpy as np
print(np.version.version)

1.20.1


In [13]:
ai = np.array([1,2,3])
aj = np.array([1,2,3.0])
ap = np.array([1j,2,3.0])

print(ai.dtype)
print(aj.dtype)
print(ap.dtype)


int64
float64
complex128


In [22]:
z = np.zeros(4)
print(z)

o = np.ones(12)
print(o)




print(np.zeros_like(o))
print(np.ones_like(z))

[0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1.]


In [26]:
l1 = ([1,2,3],[4,5,6])
a1 = np.array(l1)

print(l1)
print(a1)

print (a1.shape)

print (len(l1), len(l1[1]))

([1, 2, 3], [4, 5, 6])
[[1 2 3]
 [4 5 6]]
(2, 3)
2 3


In [28]:
o = np.ones((3,10))
print(o)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [31]:
b = np.linspace(-2.5 , 1.5, 20)
print(b)

[-2.5        -2.28947368 -2.07894737 -1.86842105 -1.65789474 -1.44736842
 -1.23684211 -1.02631579 -0.81578947 -0.60526316 -0.39473684 -0.18421053
  0.02631579  0.23684211  0.44736842  0.65789474  0.86842105  1.07894737
  1.28947368  1.5       ]


In [33]:
c = np.arange(-2.5 ,1.5, 20)
print(c)
#shit !!!!!!!!!!!!!!!!!!!!!!!!!!!!!

[-2.5]


In [34]:
x = np.linspace(0,3.14,100)
print(x)

[0.         0.03171717 0.06343434 0.09515152 0.12686869 0.15858586
 0.19030303 0.2220202  0.25373737 0.28545455 0.31717172 0.34888889
 0.38060606 0.41232323 0.4440404  0.47575758 0.50747475 0.53919192
 0.57090909 0.60262626 0.63434343 0.66606061 0.69777778 0.72949495
 0.76121212 0.79292929 0.82464646 0.85636364 0.88808081 0.91979798
 0.95151515 0.98323232 1.01494949 1.04666667 1.07838384 1.11010101
 1.14181818 1.17353535 1.20525253 1.2369697  1.26868687 1.30040404
 1.33212121 1.36383838 1.39555556 1.42727273 1.4589899  1.49070707
 1.52242424 1.55414141 1.58585859 1.61757576 1.64929293 1.6810101
 1.71272727 1.74444444 1.77616162 1.80787879 1.83959596 1.87131313
 1.9030303  1.93474747 1.96646465 1.99818182 2.02989899 2.06161616
 2.09333333 2.12505051 2.15676768 2.18848485 2.22020202 2.25191919
 2.28363636 2.31535354 2.34707071 2.37878788 2.41050505 2.44222222
 2.47393939 2.50565657 2.53737374 2.56909091 2.60080808 2.63252525
 2.66424242 2.6959596  2.72767677 2.75939394 2.79111111 2.82282

In [35]:
m = np.logspace(2,7,10)
print(m)

[1.00000000e+02 3.59381366e+02 1.29154967e+03 4.64158883e+03
 1.66810054e+04 5.99484250e+04 2.15443469e+05 7.74263683e+05
 2.78255940e+06 1.00000000e+07]


In [39]:
y = np.sin(x)
print(y)

[0.         0.03171185 0.06339181 0.095008   0.12652862 0.15792197
 0.18915646 0.22020069 0.25102341 0.28159363 0.3118806  0.34185385
 0.37148323 0.40073894 0.42959154 0.45801202 0.48597179 0.51344273
 0.54039719 0.56680807 0.5926488  0.61789339 0.64251645 0.6664932
 0.68979953 0.71241199 0.73430784 0.75546506 0.77586235 0.79547922
 0.81429591 0.83229351 0.8494539  0.86575984 0.88119491 0.8957436
 0.90939126 0.92212416 0.93392951 0.94479543 0.95471098 0.96366619
 0.97165205 0.97866054 0.98468459 0.98971816 0.99375617 0.99679457
 0.9988303  0.99986131 0.99988657 0.99890604 0.99692072 0.99393261
 0.9899447  0.98496101 0.97898656 0.97202735 0.96409038 0.95518364
 0.94531608 0.93449763 0.92273918 0.91005255 0.89645051 0.88194673
 0.8665558  0.85029321 0.83317531 0.81521933 0.79644332 0.77686618
 0.75650759 0.73538803 0.71352875 0.69095173 0.66767969 0.64373604
 0.61914485 0.59393087 0.56811946 0.54173658 0.51480877 0.48736311
 0.45942722 0.4310292  0.4021976  0.37296144 0.34335012 0.313393