In [4]:
import numpy as np 
import numpy.ma as ma


x = np.array([1,2,3,4,5])
mx = ma.masked_array(x, mask=[0,0,0,1,0])
mx2 = ma.masked_array(x, mask=[True,True, 0,0,0])

print(mx2)
print(x.mean())
print(mx.mean())


[-- -- 3 4 5]
3.0
2.75


In [6]:
a = np.arange(1000) 

print(a.sum())

print(np.sum(a))

499500
499500


In [10]:
x1 = np.array([1,2,3,4],float)
x2 = np.matrix(x1)

print(x2)

[[1. 2. 3. 4.]]


In [12]:
A = np.identity(3)
print(A)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
a =  np.matrix(A) * 5
print(A)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
